[package]
name = "a1-stack-analyser"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.83"
futures = "0.3.31"
lazy_static = "1.5.0"
regex = "1.11.1"
serial_test = "3.2.0"
uuid = { version = "1.11.0", features = ["v4"] }
