import type { AllowedKeys, TechItem } from '../types/techs.js';

export const listTech: TechItem[] = [
  { key: 'adminer', name: 'Adminer', type: 'tool' },
  { key: 'adobe', name: 'Adobe', type: 'saas' },
  { key: 'adobecommercecloud', name: 'Adobe Commerce Cloud', type: 'cloud' },
  { key: 'adyen', name: 'Adyen', type: 'saas' },
  { key: 'airbyte', name: 'Airbyte', type: 'etl' },
  { key: 'airtable', name: 'Airtable', type: 'saas' },
  { key: 'algolia', name: 'Algolia', type: 'saas' },
  { key: 'alibabacloud', name: 'Alibaba Cloud', type: 'cloud' },
  { key: 'alpinejs', name: 'Alpine.js', type: 'tool' },
  { key: 'amplitude', name: 'Amplitude Analytics', type: 'analytics' },
  { key: 'angular', name: 'Angular', type: 'language' },
  { key: 'ansible', name: 'Ansible', type: 'tool' },
  { key: 'apache_airflow', name: 'Apache Airflow', type: 'etl' },
  { key: 'apache_cassandra', name: 'Apache Cassandra', type: 'db' },
  { key: 'apache_couchdb', name: 'Apache CouchDB', type: 'db' },
  { key: 'apache_flink', name: 'Apache Flink', type: 'etl' },
  { key: 'apache_hadoop', name: 'Apache Hadoop', type: 'db' },
  { key: 'apache_hive', name: 'Apache Hive', type: 'db' },
  { key: 'apache_iceberg', name: 'Apache Iceberg', type: 'db' },
  { key: 'apache_kafka', name: 'Apache Kafka', type: 'db' },
  { key: 'apache_solr', name: 'Apache Solr', type: 'db' },
  { key: 'apache_spark', name: 'Apache Spark', type: 'db' },
  { key: 'apache_storm', name: 'Apache Storm', type: 'etl' },
  { key: 'apache_thrift', name: 'Apache Thrift', type: 'tool' },
  { key: 'apiplatform', name: 'Api Platform', type: 'tool' },
  { key: 'appveyor', name: 'AppVeyor', type: 'ci' },
  { key: 'assemble', name: 'Assemble', type: 'framework' },
  { key: 'astro', name: 'Astro', type: 'framework' },
  { key: 'atlasgo', name: 'AtlasGo', type: 'tool' },
  { key: 'atlassian', name: 'Atlassian', type: 'cloud' },
  { key: 'atlassian.bitbucket', name: 'atlassian.Bitbucket', type: 'saas' },
  { key: 'atlassian.confluence', name: 'Confluence', type: 'saas' },
  { key: 'atlassian.jira', name: 'Jira', type: 'saas' },
  { key: 'atlassian.opsgenie', name: 'Atlassian OpsGenie', type: 'saas' },
  { key: 'atlassian.trello', name: 'Atlassian Trello', type: 'saas' },
  { key: 'auth0', name: 'Auth0', type: 'saas' },
  { key: 'aws', name: 'AWS', type: 'cloud' },
  { key: 'aws.amplifyhosting', name: 'AWS Amplify Hosting', type: 'hosting' },
  { key: 'aws.apigateway', name: 'AWS Api Gateway', type: 'hosting' },
  { key: 'aws.athena', name: 'AWS Athena', type: 'db' },
  { key: 'aws.cloudformation', name: 'AWS CloudFormation', type: 'api' },
  { key: 'aws.cloudfront', name: 'AWS CloudFront', type: 'storage' },
  { key: 'aws.cloudsearch', name: 'AWS Cloudsearch', type: 'db' },
  { key: 'aws.cloudwatch', name: 'AWS Cloudwatch', type: 'monitoring' },
  { key: 'aws.codebuild', name: 'AWS Code Build', type: 'api' },
  { key: 'aws.documentdb', name: 'AWS Document DB', type: 'db' },
  { key: 'aws.dynamodb', name: 'AWS DynamoDB', type: 'db' },
  { key: 'aws.ebs', name: 'AWS Block Storage', type: 'storage' },
  { key: 'aws.ec2', name: 'AWS Compute', type: 'hosting' },
  { key: 'aws.ecr', name: 'AWS Container Registry', type: 'storage' },
  { key: 'aws.ecs', name: 'AWS Container', type: 'hosting' },
  { key: 'aws.efs', name: 'AWS File System', type: 'storage' },
  { key: 'aws.eks', name: 'AWS Kubernetes', type: 'hosting' },
  { key: 'aws.elasticache', name: 'AWS ElastiCache', type: 'db' },
  { key: 'aws.fargate', name: 'AWS Fargate', type: 'hosting' },
  { key: 'aws.glacier', name: 'AWS Glacier', type: 'storage' },
  { key: 'aws.glue', name: 'AWS Glue', type: 'etl' },
  { key: 'aws.kafka', name: 'AWS Kafka', type: 'db' },
  { key: 'aws.kinesis', name: 'AWS Kinesis', type: 'api' },
  { key: 'aws.kms', name: 'AWS Kms', type: 'api' },
  { key: 'aws.lambda', name: 'AWS Lambda', type: 'hosting' },
  { key: 'aws.lightsail', name: 'AWS Lightsail', type: 'hosting' },
  { key: 'aws.memorydb', name: 'AWS MemoryDB', type: 'db' },
  { key: 'aws.mq', name: 'AWS ActiveMQ', type: 'messaging' },
  { key: 'aws.neptune', name: 'AWS Neptune', type: 'db' },
  { key: 'aws.opensearch', name: 'AWS Opensearch', type: 'db' },
  { key: 'aws.polly', name: 'AWS Polly', type: 'api' },
  { key: 'aws.rds', name: 'AWS RDS', type: 'db' },
  { key: 'aws.redshift', name: 'AWS Redshift', type: 'db' },
  { key: 'aws.rekognition', name: 'AWS Rekognition', type: 'api' },
  { key: 'aws.s3', name: 'AWS S3', type: 'storage' },
  { key: 'aws.sagemaker', name: 'AWS SageMaker', type: 'db' },
  { key: 'aws.secretsmanager', name: 'AWS Secrets Manager', type: 'db' },
  { key: 'aws.ses', name: 'AWS Simple Email Service', type: 'messaging' },
  { key: 'aws.sfn', name: 'AWS Step Functions', type: 'api' },
  { key: 'aws.sns', name: 'AWS Notification Service', type: 'messaging' },
  { key: 'aws.sqs', name: 'AWS SQS', type: 'messaging' },
  { key: 'aws.timestream', name: 'AWS Timestream', type: 'db' },
  { key: 'aws.translate', name: 'AWS Translate', type: 'api' },
  { key: 'azure', name: 'Azure', type: 'cloud' },
  { key: 'azure.aks', name: 'Azure Kubernetes', type: 'hosting' },
  { key: 'azure.ci', name: 'AzureCI', type: 'ci' },
  { key: 'azure.cosmosdb', name: 'Azure Cosmos DB', type: 'db' },
  { key: 'azure.functions', name: 'Azure Functions', type: 'hosting' },
  { key: 'azure.mariadb', name: 'Azure MariaDB', type: 'db' },
  { key: 'azure.mysql', name: 'Azure MySQL', type: 'db' },
  { key: 'azure.postgres', name: 'Azure Postgres', type: 'db' },
  { key: 'azure.redis', name: 'Azure Redis', type: 'db' },
  { key: 'azure.sql', name: 'Azure SQL', type: 'db' },
  { key: 'azure.staticwebapps', name: 'Azure Static Web Apps', type: 'hosting' },
  { key: 'azure.storage', name: 'Azure Storage', type: 'storage' },
  { key: 'bash', name: 'Bash', type: 'language' },
  { key: 'betterstack', name: 'Better Stack', type: 'monitoring' },
  { key: 'bigcommerce', name: 'BigCommerce', type: 'saas' },
  { key: 'blackfire', name: 'Blackfire', type: 'monitoring' },
  { key: 'blitzjs', name: 'Blitzjs', type: 'framework' },
  { key: 'bootstrap', name: 'Bootstrap', type: 'tool' },
  { key: 'box', name: 'Box', type: 'saas' },
  { key: 'brevo', name: 'Brevo', type: 'saas' },
  { key: 'browserstack', name: 'Browserstack', type: 'ci' },
  { key: 'bytebase', name: 'Bytebase', type: 'tool' },
  { key: 'c', name: 'C', type: 'language' },
  { key: 'caddy', name: 'Caddy', type: 'app' },
  { key: 'celery', name: 'Celery', type: 'messaging' },
  { key: 'checkov', name: 'Checkov', type: 'tool' },
  { key: 'chef', name: 'Chef', type: 'tool' },
  { key: 'circleci', name: 'CircleCI', type: 'ci' },
  { key: 'cirrusci', name: 'CirrusCI', type: 'ci' },
  { key: 'clickhouse', name: 'Clickhouse', type: 'db' },
  { key: 'clicksend', name: 'ClickSend', type: 'saas' },
  { key: 'cloudbees', name: 'CloudBees', type: 'cloud' },
  { key: 'cloudbees.codeship', name: 'CloudBees Codeship', type: 'ci' },
  { key: 'cloudflare', name: 'Cloudflare', type: 'cloud' },
  { key: 'cloudflare.pages', name: 'Cloudflare Pages', type: 'hosting' },
  { key: 'cloudflare.workers', name: 'Cloudflare Workers', type: 'hosting' },
  { key: 'cockroachdb', name: 'CockroachDB', type: 'db' },
  { key: 'codecov', name: 'Codecov', type: 'ci' },
  { key: 'codesandboxci', name: 'CodeSandboxCI', type: 'ci' },
  { key: 'commercetools', name: 'Commercetools', type: 'saas' },
  { key: 'consul', name: 'Consul', type: 'app' },
  { key: 'contenful', name: 'Contentful', type: 'saas' },
  { key: 'couchbase', name: 'Couchbase', type: 'db' },
  { key: 'coveralls', name: 'Coveralls', type: 'ci' },
  { key: 'cplusplus', name: 'C++', type: 'language' },
  { key: 'cratedb', name: 'CrateDB', type: 'db' },
  { key: 'crowdin', name: 'Crodwin', type: 'saas' },
  { key: 'csharp', name: 'C#', type: 'language' },
  { key: 'css', name: 'CSS', type: 'language' },
  { key: 'cypressci', name: 'CypressCI', type: 'ci' },
  { key: 'd3js', name: 'D3.js', type: 'tool' },
  { key: 'dart', name: 'Dart', type: 'language' },
  { key: 'databricks', name: 'Databricks', type: 'etl' },
  { key: 'datadog', name: 'Datadog', type: 'monitoring' },
  { key: 'dataiku', name: 'Dataiku', type: 'etl' },
  { key: 'datastax', name: 'Datastax', type: 'db' },
  { key: 'datocms', name: 'Dato CMS', type: 'saas' },
  { key: 'deferrun', name: 'Defer.run', type: 'saas' },
  { key: 'deno', name: 'Deno', type: 'language' },
  { key: 'denodeploy', name: 'Deno Deploy', type: 'hosting' },
  { key: 'dependabot', name: 'Dependabot', type: 'ci' },
  { key: 'digitalocean', name: 'DigitalOcean', type: 'hosting' },
  { key: 'discord', name: 'Discord', type: 'saas' },
  { key: 'discourse', name: 'Discourse', type: 'app' },
  { key: 'docker', name: 'Docker', type: 'tool' },
  { key: 'doctrinephp', name: 'Doctrine', type: 'tool' },
  { key: 'docusaurus', name: 'Docusaurus', type: 'framework' },
  { key: 'docusign', name: 'Docusign', type: 'saas' },
  { key: 'droneci', name: 'DroneCI', type: 'ci' },
  { key: 'dropbox', name: 'Dropbox', type: 'saas' },
  { key: 'drupal', name: 'Drupal', type: 'framework' },
  { key: 'duckdb', name: 'DuckDB', type: 'db' },
  { key: 'dynatrace', name: 'Dynatrace', type: 'saas' },
  { key: 'elasticcloud', name: 'Elastic Cloud', type: 'hosting' },
  { key: 'elasticsearch', name: 'Elasticsearch', type: 'db' },
  { key: 'elasticstack', name: 'Elasticstack', type: 'hosting' },
  { key: 'electron', name: 'Electron', type: 'tool' },
  { key: 'eleventy', name: 'Eleventy', type: 'framework' },
  { key: 'elixir', name: 'Elixir', type: 'language' },
  { key: 'emberjs', name: 'Ember', type: 'framework' },
  { key: 'equinix', name: 'Equinix', type: 'cloud' },
  { key: 'esbuild', name: 'Esbuild', type: 'tool' },
  { key: 'eslint', name: 'Eslint', type: 'tool' },
  { key: 'expodev', name: 'Expo.dev', type: 'hosting' },
  { key: 'expojs', name: 'ExpoJS', type: 'framework' },
  { key: 'express', name: 'Express', type: 'tool' },
  { key: 'fabric', name: 'Fabric', type: 'saas' },
  { key: 'facebook', name: 'Facebook', type: 'saas' },
  { key: 'fastify', name: 'Fastify', type: 'tool' },
  { key: 'fastly', name: 'Fastly', type: 'hosting' },
  { key: 'figma', name: 'Figma', type: 'saas' },
  { key: 'firebase', name: 'Hosting', type: 'cloud' },
  { key: 'firebase.firestore', name: 'Firebase Firestore', type: 'db' },
  { key: 'flyio', name: 'Flyio', type: 'cloud' },
  { key: 'flyway', name: 'Flyway', type: 'tool' },
  { key: 'gatsby', name: 'Gatsby', type: 'tool' },
  { key: 'gcp', name: 'Google Cloud Platform', type: 'cloud' },
  { key: 'gcp.aiplatform', name: 'Cloud AI Platform', type: 'api' },
  { key: 'gcp.appengine', name: 'Google App Engine', type: 'hosting' },
  { key: 'gcp.artifactregistry', name: 'Cloud Artifact Registry', type: 'storage' },
  { key: 'gcp.bigquery', name: 'Google BigQuery', type: 'db' },
  { key: 'gcp.bigtable', name: 'Cloud BigTable', type: 'db' },
  { key: 'gcp.cloudbuild', name: 'Cloud Build', type: 'api' },
  { key: 'gcp.cloudrun', name: 'Cloud Run', type: 'hosting' },
  { key: 'gcp.containerregistry', name: 'Cloud Container Registry', type: 'storage' },
  { key: 'gcp.dataflow', name: 'Cloud Dataflow', type: 'etl' },
  { key: 'gcp.dataproc', name: 'Cloud Dataproc', type: 'etl' },
  { key: 'gcp.datastore', name: 'Cloud Datastore', type: 'db' },
  { key: 'gcp.dialogflow', name: 'Cloud Dialogflow', type: 'api' },
  { key: 'gcp.dns', name: 'Google DNS', type: 'network' },
  { key: 'gcp.functions', name: 'Cloud Functions', type: 'hosting' },
  { key: 'gcp.gce', name: 'Google Compute', type: 'hosting' },
  { key: 'gcp.gcs', name: 'Cloud Storage', type: 'storage' },
  { key: 'gcp.gke', name: 'Google Kubernetes', type: 'hosting' },
  { key: 'gcp.kms', name: 'Cloud Key Management', type: 'api' },
  { key: 'gcp.language', name: 'Cloud Language', type: 'api' },
  { key: 'gcp.logging', name: 'Cloud Logging', type: 'monitoring' },
  { key: 'gcp.maps', name: 'Google Maps', type: 'api' },
  { key: 'gcp.memorystore', name: 'Google Cloud Memorystore', type: 'db' },
  { key: 'gcp.pubsub', name: 'PubSub', type: 'messaging' },
  { key: 'gcp.secretmanager', name: 'Cloud Secret Manager', type: 'db' },
  { key: 'gcp.spanner', name: 'Cloud Spanner', type: 'db' },
  { key: 'gcp.speech', name: 'Cloud Speech', type: 'api' },
  { key: 'gcp.sql', name: 'Cloud SQL', type: 'db' },
  { key: 'gcp.tasks', name: 'Cloud Tasks', type: 'hosting' },
  { key: 'gcp.translate', name: 'Google Translate', type: 'api' },
  { key: 'gcp.vision', name: 'Cloud Vision', type: 'api' },
  { key: 'ghost', name: 'Ghost', type: 'framework' },
  { key: 'gitbook', name: 'Gitbook', type: 'saas' },
  { key: 'gitguardian', name: 'GitGuardian', type: 'saas' },
  { key: 'github', name: 'GitHub', type: 'saas' },
  { key: 'github.actions', name: 'Github Actions', type: 'ci' },
  { key: 'github.pages', name: 'Github Pages', type: 'hosting' },
  { key: 'gitlab', name: 'Gitlab', type: 'tool' },
  { key: 'gitlab.ci', name: 'Gitlab CI', type: 'ci' },
  { key: 'goacmelego', name: 'Lego', type: 'tool' },
  { key: 'golang', name: 'Golang', type: 'language' },
  { key: 'golangcilint', name: 'GolangCI Lint', type: 'tool' },
  { key: 'googleanalytics', name: 'Google Analytics', type: 'analytics' },
  { key: 'grafana', name: 'Grafana', type: 'app' },
  { key: 'gridsome', name: 'Gridsome', type: 'framework' },
  { key: 'haproxy', name: 'HAProxy', type: 'app' },
  { key: 'hashicorp_vault', name: 'Vault', type: 'db' },
  { key: 'healthchecksio', name: 'Healthchecks.io', type: 'monitoring' },
  { key: 'helm', name: 'Helm', type: 'tool' },
  { key: 'heroku', name: 'Heroku', type: 'cloud' },
  { key: 'hexojs', name: 'HexoJS', type: 'framework' },
  { key: 'hotjar', name: 'Hotjar', type: 'saas' },
  { key: 'httpd', name: 'HTTPD', type: 'app' },
  { key: 'hubspot', name: 'HubSpot', type: 'saas' },
  { key: 'huggingface', name: 'Hugging Face', type: 'saas' },
  { key: 'hugo', name: 'Hugo', type: 'framework' },
  { key: 'hyperdx', name: 'HyperDX', type: 'monitoring' },
  { key: 'hypertune', name: 'Hypertune', type: 'saas' },
  { key: 'ibmcloud', name: 'IBM Cloud', type: 'cloud' },
  { key: 'iftt', name: 'iftt', type: 'saas' },
  { key: 'influxdb', name: 'InfluxDB', type: 'db' },
  { key: 'intercom', name: 'Intercom', type: 'saas' },
  { key: 'intuit', name: 'Intuit', type: 'saas' },
  { key: 'java', name: 'Java', type: 'language' },
  { key: 'jekyll', name: 'Jekyll', type: 'framework' },
  { key: 'jenkins', name: 'Jenkins', type: 'ci' },
  { key: 'joomla', name: 'Joomla!', type: 'framework' },
  { key: 'k6', name: 'Grafana K6', type: 'tool' },
  { key: 'kentico', name: 'Kentico', type: 'saas' },
  { key: 'kibana', name: 'Kibana', type: 'app' },
  { key: 'klarna', name: 'Klarna', type: 'saas' },
  { key: 'klaviyo', name: 'Klaviyo', type: 'saas' },
  { key: 'koa', name: 'Koa', type: 'tool' },
  { key: 'koalaanalytics', name: 'Koala Analytics', type: 'analytics' },
  { key: 'kong', name: 'Kong', type: 'app' },
  { key: 'koyeb', name: 'Koyeb', type: 'hosting' },
  { key: 'kubernetes', name: 'Kubernetes', type: 'hosting' },
  { key: 'lago', name: 'Lago', type: 'saas' },
  { key: 'laravel', name: 'Laravel', type: 'framework' },
  { key: 'launchdarkly', name: 'LaunchDarkly', type: 'saas' },
  { key: 'lemonsqueezy', name: 'Lemon Squeezy', type: 'saas' },
  { key: 'lighthouse', name: 'Lighthouse', type: 'tool' },
  { key: 'linear', name: 'Linear', type: 'saas' },
  { key: 'liquibase', name: 'Liquibase', type: 'tool' },
  { key: 'logrocket', name: 'LogRocket', type: 'saas' },
  { key: 'logsnag', name: 'LogSnag', type: 'analytics' },
  { key: 'logstash', name: 'Logstash', type: 'etl' },
  { key: 'magento', name: 'Magento', type: 'framework' },
  { key: 'mailchimp', name: 'Mailchimp', type: 'saas' },
  { key: 'mailgun', name: 'Mailgun', type: 'saas' },
  { key: 'mailhog', name: 'Mailhog', type: 'tool' },
  { key: 'mailjet', name: 'Mailjet', type: 'saas' },
  { key: 'mariadb', name: 'MariaDB', type: 'db' },
  { key: 'matomo', name: 'Matomo', type: 'analytics' },
  { key: 'mattermost', name: 'Mattermost', type: 'saas' },
  { key: 'meilisearch', name: 'Meilisearch', type: 'db' },
  { key: 'meilisearchcloud', name: 'Meilisearch Cloud', type: 'db' },
  { key: 'memcached', name: 'Memcached', type: 'db' },
  { key: 'meteorjs', name: 'Meteor', type: 'framework' },
  { key: 'milvusdb', name: 'MilvusDB', type: 'db' },
  { key: 'mithriljs', name: 'Mithril', type: 'tool' },
  { key: 'mixpanel', name: 'Mixpanel', type: 'analytics' },
  { key: 'mongodb', name: 'MongoDB', type: 'db' },
  { key: 'mongodbatlas', name: 'MongoDB Atlas', type: 'hosting' },
  { key: 'mongoexpress', name: 'Mongo Express', type: 'tool' },
  { key: 'mysql', name: 'Mysql', type: 'db' },
  { key: 'nats', name: 'Nats', type: 'messaging' },
  { key: 'neo4j', name: 'Neo4j', type: 'db' },
  { key: 'neondb', name: 'NeonDB', type: 'db' },
  { key: 'netlify', name: 'Netlify', type: 'cloud' },
  { key: 'newrelic', name: 'New Relic', type: 'monitoring' },
  { key: 'nextcloud', name: 'Nextcloud', type: 'cloud' },
  { key: 'nextjs', name: 'Next.js', type: 'framework' },
  { key: 'nginx', name: 'Nginx', type: 'app' },
  { key: 'nodejs', name: 'NodeJS', type: 'language' },
  { key: 'notion', name: 'Notion', type: 'saas' },
  { key: 'novu', name: 'Novy', type: 'saas' },
  { key: 'nuxtjs', name: 'Nuxt.js', type: 'framework' },
  { key: 'oceanbase', name: 'Oceanbase', type: 'db' },
  { key: 'okta', name: 'Okta', type: 'saas' },
  { key: 'onlineornot', name: 'OnlineOrNot', type: 'monitoring' },
  { key: 'openai', name: 'Openai', type: 'saas' },
  { key: 'optimizely', name: 'Optimizely', type: 'saas' },
  { key: 'oraclecloud', name: 'Oracle Cloud', type: 'cloud' },
  { key: 'ovh', name: 'OVH', type: 'cloud' },
  { key: 'ovh.database', name: 'OVH Database', type: 'db' },
  { key: 'ovh.dedicated', name: 'OVH Dedicated Server', type: 'hosting' },
  { key: 'ovh.kubernetes', name: 'OVH Kubernetes', type: 'hosting' },
  { key: 'ovh.storage', name: 'OVH Storage', type: 'storage' },
  { key: 'ovh.vps', name: 'OVH VPS', type: 'hosting' },
  { key: 'pagerduty', name: 'Pagerduty', type: 'saas' },
  { key: 'papertrail', name: 'Papertrail', type: 'monitoring' },
  { key: 'payloadcms', name: 'Payload', type: 'framework' },
  { key: 'paypal', name: 'Paypal', type: 'saas' },
  { key: 'percona', name: 'Percona', type: 'db' },
  { key: 'phaserjs', name: 'Phaser', type: 'framework' },
  { key: 'php', name: 'PHP', type: 'language' },
  { key: 'phppest', name: 'PHP Pest', type: 'tool' },
  { key: 'phpstan', name: 'PHPStan', type: 'tool' },
  { key: 'phpunit', name: 'PHPUnit', type: 'tool' },
  { key: 'pingdom', name: 'Pingdom', type: 'monitoring' },
  { key: 'pirschanalytics', name: 'Pirsch Analytics', type: 'analytics' },
  { key: 'placekit', name: 'PlaceKit', type: 'saas' },
  { key: 'planetscale', name: 'PlanetScale', type: 'db' },
  { key: 'platformsh', name: 'Platform.sh', type: 'hosting' },
  { key: 'plausible', name: 'Plausible', type: 'analytics' },
  { key: 'playwright', name: 'Playwright', type: 'tool' },
  { key: 'postgresql', name: 'Postgres', type: 'db' },
  { key: 'posthog', name: 'PostHog', type: 'analytics' },
  { key: 'postman', name: 'Postman', type: 'saas' },
  { key: 'postmark', name: 'Postmark', type: 'saas' },
  { key: 'preactjs', name: 'Preact', type: 'tool' },
  { key: 'prestashop', name: 'Prestashop', type: 'framework' },
  { key: 'prettier', name: 'Prettier', type: 'tool' },
  { key: 'prisma', name: 'Prisma', type: 'tool' },
  { key: 'prismacloud', name: 'Prisma Cloud', type: 'saas' },
  { key: 'prometheus', name: 'Prometheus', type: 'monitoring' },
  { key: 'puppeteer', name: 'Puppeteer', type: 'tool' },
  { key: 'python', name: 'Python', type: 'language' },
  { key: 'qdrant', name: 'Qdrant', type: 'db' },
  { key: 'qovery', name: 'Qovery', type: 'cloud' },
  { key: 'qovery.cluster', name: 'Qovery Cluster', type: 'hosting' },
  { key: 'qovery.database', name: 'Qovery Database', type: 'db' },
  { key: 'questdb', name: 'QuestDB', type: 'db' },
  { key: 'rabbitmq', name: 'RabbitMQ', type: 'messaging' },
  { key: 'railway', name: 'Railway', type: 'cloud' },
  { key: 'railway.mongodb', name: 'Railway MongoDB', type: 'db' },
  { key: 'railway.mysql', name: 'Railway MySQL', type: 'db' },
  { key: 'railway.postgres', name: 'Railway Postgres', type: 'db' },
  { key: 'railway.redis', name: 'Railway Redis', type: 'db' },
  { key: 'react', name: 'React', type: 'language' },
  { key: 'reactemail', name: 'React Email', type: 'tool' },
  { key: 'redis', name: 'Redis', type: 'db' },
  { key: 'redwoodjs', name: 'RedwoodJs', type: 'framework' },
  { key: 'refinedev', name: 'Refine', type: 'framework' },
  { key: 'relativeci', name: 'RelativeCI', type: 'ci' },
  { key: 'remixrun', name: 'Remix', type: 'framework' },
  { key: 'render', name: 'Render', type: 'hosting' },
  { key: 'renovate', name: 'Renovate', type: 'ci' },
  { key: 'replit', name: 'Replit', type: 'hosting' },
  { key: 'replit.database', name: 'Replit Database', type: 'db' },
  { key: 'replit.postgres', name: 'Replit Postgres', type: 'db' },
  { key: 'resend', name: 'Resend', type: 'saas' },
  { key: 'rethinkdb', name: 'RethinkDB', type: 'db' },
  { key: 'rollbar', name: 'Rollbar', type: 'monitoring' },
  { key: 'rollup', name: 'Rollup', type: 'tool' },
  { key: 'ruby', name: 'Ruby', type: 'language' },
  { key: 'rust', name: 'Rust', type: 'language' },
  { key: 'salesforce', name: 'Salesforce', type: 'saas' },
  { key: 'sanity', name: 'Sanity', type: 'saas' },
  { key: 'sap', name: 'SAP', type: 'saas' },
  { key: 'sas', name: 'SAS', type: 'saas' },
  { key: 'scaleway', name: 'Scaleway', type: 'cloud' },
  { key: 'scaleway.container', name: 'Scaleway Container', type: 'hosting' },
  { key: 'scaleway.database', name: 'Scaleway Database', type: 'db' },
  { key: 'scaleway.documentdb', name: 'Scaleway DocumentDB', type: 'db' },
  { key: 'scaleway.elasticmetal', name: 'Scaleway Elastic Metal', type: 'hosting' },
  { key: 'scaleway.function', name: 'Scaleway Function', type: 'hosting' },
  { key: 'scaleway.kubernetes', name: 'Scaleway Kubernetes', type: 'hosting' },
  { key: 'scaleway.mq', name: 'Scaleway M&Q', type: 'messaging' },
  { key: 'scaleway.redis', name: 'Scaleway Redis', type: 'db' },
  { key: 'scaleway.secretmanager', name: 'Scaleway Secret Manager', type: 'db' },
  { key: 'scaleway.storage', name: 'Scaleway Storage', type: 'storage' },
  { key: 'scoutapm', name: 'Scout APM', type: 'monitoring' },
  { key: 'scss', name: 'SCSS', type: 'language' },
  { key: 'selenium', name: 'Selenium', type: 'tool' },
  { key: 'sendgrid', name: 'Sendgrid', type: 'saas' },
  { key: 'sentry', name: 'Sentry', type: 'monitoring' },
  { key: 'sequelize', name: 'Sequelize', type: 'tool' },
  { key: 'servicenow', name: 'ServiceNow', type: 'saas' },
  { key: 'shopify', name: 'Shopify', type: 'saas' },
  { key: 'shopify.hydrogen', name: 'Shopify Hydrogen', type: 'framework' },
  { key: 'signoz', name: 'Signoz', type: 'monitoring' },
  { key: 'sitecore', name: 'Sitecore', type: 'hosting' },
  { key: 'sitecore.xmlcloud', name: 'Sitecore XM cloud', type: 'api' },
  { key: 'slack', name: 'Slack', type: 'saas' },
  { key: 'snowflake', name: 'Snowflake', type: 'db' },
  { key: 'snyk', name: 'Snyk', type: 'saas' },
  { key: 'socketio', name: 'Socket.io', type: 'tool' },
  { key: 'solidjs', name: 'Solid js', type: 'language' },
  { key: 'sonarcloud', name: 'SonarCloud', type: 'ci' },
  { key: 'sonarlint', name: 'SonarLint', type: 'tool' },
  { key: 'sonarqube', name: 'SonarQube', type: 'tool' },
  { key: 'splitio', name: 'Split', type: 'saas' },
  { key: 'splunk', name: 'Splunk', type: 'saas' },
  { key: 'sqlite', name: 'SQLite', type: 'db' },
  { key: 'sqreen', name: 'Sqreen', type: 'saas' },
  { key: 'squarespace', name: 'Squarespace', type: 'saas' },
  { key: 'squareup', name: 'Square', type: 'saas' },
  { key: 'storybook', name: 'Storybook', type: 'tool' },
  { key: 'strapi', name: 'Strapi', type: 'framework' },
  { key: 'stripe', name: 'Stripe', type: 'saas' },
  { key: 'styleci', name: 'StyleCI', type: 'ci' },
  { key: 'stylelint', name: 'Stylelint', type: 'tool' },
  { key: 'supabase', name: 'Supabase', type: 'cloud' },
  { key: 'supabase.functions', name: 'Supabase Functions', type: 'hosting' },
  { key: 'supabase.postgres', name: 'Supabase Postgres', type: 'db' },
  { key: 'supabase.realtime', name: 'Supabase Realtime', type: 'messaging' },
  { key: 'supabase.storage', name: 'Supabase Storage', type: 'storage' },
  { key: 'surrealdb', name: 'SurrealDB', type: 'db' },
  { key: 'sveltejs', name: 'Svelte', type: 'language' },
  { key: 'symfony', name: 'Symfony', type: 'framework' },
  { key: 'tailwind', name: 'Tailwind', type: 'tool' },
  { key: 'tdengine', name: 'TDengine', type: 'db' },
  { key: 'teamcity', name: 'TeamCity', type: 'ci' },
  { key: 'teamspeak', name: 'Teamspeak', type: 'app' },
  { key: 'telegraf', name: 'Telegraf', type: 'app' },
  { key: 'telegram', name: 'Telegram', type: 'saas' },
  { key: 'tencentcloud', name: 'Tencent Cloud', type: 'hosting' },
  { key: 'tensorflow', name: 'Tensorflow', type: 'tool' },
  { key: 'terraform', name: 'Terraform', type: 'tool' },
  { key: 'terragrunt', name: 'Terragrunt', type: 'tool' },
  { key: 'tidb', name: 'TiDB', type: 'db' },
  { key: 'timescaledb', name: 'TimescaleDB', type: 'db' },
  { key: 'tinybird', name: 'Tinybird', type: 'analytics' },
  { key: 'traefik', name: 'Traefik', type: 'app' },
  { key: 'travisci', name: 'TravisCI', type: 'ci' },
  { key: 'trufflesecurity', name: 'Truffle Security', type: 'ci' },
  { key: 'twigphp', name: 'Twig', type: 'tool' },
  { key: 'twilio', name: 'Twilio', type: 'saas' },
  { key: 'twitter', name: 'X', type: 'saas' },
  { key: 'typescript', name: 'Typescript', type: 'language' },
  { key: 'typesense', name: 'Typesense', type: 'db' },
  { key: 'typesensecloud', name: 'Typesense Cloud', type: 'db' },
  { key: 'upstash', name: 'Upstash', type: 'cloud' },
  { key: 'upstash.kafka', name: 'Upstash Kafka', type: 'db' },
  { key: 'upstash.qstash', name: 'Upstash QStash', type: 'db' },
  { key: 'upstash.redis', name: 'Upstash Redis', type: 'db' },
  { key: 'uptimekuma', name: 'Uptime Kuma', type: 'monitoring' },
  { key: 'vale', name: 'Vale', type: 'tool' },
  { key: 'vercel', name: 'Vercel', type: 'cloud' },
  { key: 'vercel.ai', name: 'Vercel AI', type: 'api' },
  { key: 'vercel.analytics', name: 'Vercel Analytics', type: 'analytics' },
  { key: 'vercel.blob', name: 'Vercel Blob', type: 'db' },
  { key: 'vercel.edge', name: 'Vercel Edge', type: 'hosting' },
  { key: 'vercel.kv', name: 'Vercel KV', type: 'db' },
  { key: 'vercel.postgres', name: 'Vercel Postgres', type: 'db' },
  { key: 'veriff', name: 'Veriff', type: 'saas' },
  { key: 'vialink', name: 'Vialink', type: 'saas' },
  { key: 'victoriametrics', name: 'VictoriaMetrics', type: 'db' },
  { key: 'vite', name: 'Vite', type: 'tool' },
  { key: 'vue', name: 'Vue', type: 'language' },
  { key: 'webflow', name: 'Webflow', type: 'saas' },
  { key: 'webpack', name: 'Webpack', type: 'tool' },
  { key: 'wiz', name: 'Wiz', type: 'saas' },
  { key: 'woocommerce', name: 'WooCommerce', type: 'framework' },
  { key: 'wordpress', name: 'Wordpress', type: 'framework' },
  { key: 'yii2', name: 'Yii2', type: 'framework' },
  { key: 'yousign', name: 'Yousign', type: 'saas' },
  { key: 'zapier', name: 'Zapier', type: 'saas' },
  { key: 'zendesk', name: 'Zendesk', type: 'saas' },
  { key: 'zig', name: 'Zig', type: 'language' },
  { key: 'zipkin', name: 'Zipkin', type: 'monitoring' },
  { key: 'zookeeper', name: 'Zookeeper', type: 'app' },
  { key: 'zoom', name: 'Zoom', type: 'saas' },
  { key: 'zuora', name: 'Zuora', type: 'saas' },
];

export const listIndexed: Record<AllowedKeys, TechItem> = {} as any;
Object.values(listTech).forEach((v) => {
  listIndexed[v.key] = v;
});
